### ISSUE TITLE
Dataset missing

### ISSUE THREAD

**Issue by zc2023** [sg-3d/sg3d#2]
Hi,

 I have carefully read your paper and am highly interested in your excellent work. I have a question regarding the dataset preparation.

In the data preparation step, I downloaded the Sceneverse dataset, which includes five sub-datasets. However, the links you provided for [scene_ver_aux] and [scene_ver_pred] only contain ScanNet data. It appears that the other four sub-datasets are missing. Could you clarify if these sub-datasets are included in the ScanNet.zip file, or if there is a separate link for the complete dataset?

Thank you in advance for your assistance.

**Comment by zc2023** [comment]
Lack 3RScan data in [scene_verse_aux] directory
![image](https://github.com/user-attachments/assets/f7d7e175-9b8f-40f1-ad09-ecccd5903ef0)

**Comment by dk-liang** [comment]
I met the same problem. Could the authors provide the completed dataset?

**Comment by zhuziyu-edward** [comment]
[3RScan.json](https://github.com/user-attachments/files/16939033/3RScan.json)
This file can be found in this link and is used for loading train / val split. You can also use sceneverse 3RScan train_split_non_overlap, val_split_non_overlap to replace this file.
